Business Logic Realization 2
San4ek/PracticeModsenJava pull request #17
Opened 2024-06-18 11:23 UTC by Simon-Zhuk

mappers created using MapStruct

2024-06-18 15:40 UTC, VladislavKabral commented on pom.xml
> +            <version>1.5.5.Final</version>
Версии зависимостей нужно вынести в properties

2024-06-18 15:40 UTC, VladislavKabral commented on src/main/java/com/example/practicemodsenjava/service/impl/CategoryServiceImpl.java
> +    @Autowired
Для генерации конструкторов тоже Lombok можно использовать

2024-06-18 15:40 UTC, VladislavKabral commented on src/main/java/com/example/practicemodsenjava/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new GlobalExceptionHandler("Category with id " + categoryId + " not found"));
String.format лучше здесь использовать. Сообщения ошибок лучше вынести в какой-нибудь UtilityClass. И тут ведь просто эксепшен должен пробрасываться, а не handler юзаться.

2024-06-18 15:40 UTC, VladislavKabral commented on src/main/java/com/example/practicemodsenjava/service/impl/OrderItemServiceImpl.java
> +package com.example.practicemodsenjava.service.impl;
Те же замечания

2024-06-18 16:40 UTC, San4ek requested changes

2024-06-23 10:21 UTC, San4ek approved these changes

2024-06-23 10:22 UTC, merged